# Generated by Django 5.1.4 on 2025-01-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kategori',
            table='kategori',
        ),
        migrations.AlterModelTable(
            name='produk',
            table='produk',
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
    ]
